### ISSUE TITLE
orbitDay ignored?

### ISSUE THREAD

**Issue by westgate** [KMarshland/hours-of-daylight#2]
I'm actually converting this code to python (was pretty straight forward, I can put a copy here if you wish), and I noticed a small issue, I think, or it could be a JS thing.

in the calculateHoursOfDaylight there's a parameter orbitDay, it appears like that value is being ignore, and you've got it hardcoded to 35.

when I replaced 35 with orbitDay the code appeared to work.

**Comment by KMarshland** [comment]
Good catch, thank you! I've fixed this.

Once your python library is on github, would you mind posting a link here? I'll link it in the README. Would also appreciate you linking back to this one if you're willing.

**Comment by westgate** [comment]
sure, I'd be willing.  but maybe we just post it with yours?

**Comment by KMarshland** [comment]
Sure, pull requests welcome.

**Comment by westgate** [comment]
how do we setup a pull request?

**Comment by KMarshland** [comment]
Sorry for the slow response! See this tutorial for information: https://opensource.com/article/19/7/create-pull-request-github

**Comment by westgate** [comment]
no problem. I'm not working at light speed either ... 8- )

**Comment by westgate** [comment]
this may not be the right way, but I've attached a copy of the code here.

**Comment by westgate** [comment]
did you get the code?

**Comment by KMarshland** [comment]
I did not, alas. I think a pull request (tutorial here: https://opensource.com/article/19/7/create-pull-request-github) is probably going to be the best way to get it to me.

**Comment by westgate** [comment]
ok.  I'll give it a try.
